- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: master  # or specific git tag
  hooks:
    - id: script-must-have-extension
    - id: script-must-not-have-extension
    - id: shellcheck
