#!/usr/bin/env bash
# Basic and mandatory settings for the base of an OS customization run
# Written by Gina Haeussge <gina at octoprint dot org>,
# based on work by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -ex

rm -r /usr/sbin/policy-rc.d || true

if [ -n "$EDITBASE_APT_PROXY" ]
then
  rm -r /etc/apt/apt.conf.d/02octopi_build_proxy
fi

if [ -n "$EDITBASE_PYPI_INDEX" ]
then
  rm -r /root/.pip
  rm -r /root/.pydistutils.cfg
  rm -r /home/"${BASE_USER}"/.pip/pip.conf
  rm -r /home/"${BASE_USER}"/.pydistutils.cfg
fi

if [ -f /etc/resolv.conf.link ]; then
  echo "Restoring original symlink for resolv.conf"
  resolvconf_target=$(cat /etc/resolv.conf.link)
  ln -sf "${resolvconf_target}" /etc/resolv.conf
  rm /etc/resolv.conf.link
elif [ -e /etc/resolv.conf.orig ]; then
  echo "Restoring original resolv.conf"
  [ -f /etc/resolv.conf ] && rm /etc/resolv.conf
  mv /etc/resolv.conf.orig /etc/resolv.conf || true
fi

# Remove common.sh after build (https://github.com/OctoPrint/CustoPiZer/issues/13)
if [ -f "/common.sh" ]; then
    rm -f /common.sh
fi

#cleanup
apt-get clean
apt-get autoremove -y
