#!/usr/bin/env bash
# EditBase script
# Basic and mandatory settings for the base of an OctoPi customization run
# Written by Gina Haeussge <gina at octoprint dot org>, 
# based on work by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -ex

rm -r /usr/sbin/policy-rc.d || true

if [ -n "$EDITBASE_APT_PROXY" ]
then
  rm -r /etc/apt/apt.conf.d/02octopi_build_proxy
fi

if [ -n "$EDITBASE_PYPI_INDEX" ]
then
  rm -r /root/.pip
  rm -r /root/.pydistutils.cfg
  rm -r /home/"${BASE_USER}"/.pip/pip.conf
  rm -r /home/"${BASE_USER}"/.pydistutils.cfg
fi

#cleanup
apt-get clean
apt-get autoremove -y
